app = "fly-data-shipper"
swap_size_mb = 1024

[env]
  enableTCP6=true
  retentionPeriod="30d"
  VECTOR_REQUIRE_HEALTHY=true
  GF_PATHS_DATA="/data/grafana"

[mounts]
  source="data"
  destination="/data"

[vm]
  memory = "1gb"
